server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: rate-limiter
  
  # Enable AOP for rate limiting
  aop:
    auto: true
    proxy-target-class: true

# Actuator configuration for monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# Logging configuration
logging:
  level:
    com.example.ratelimiter: DEBUG
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
